### ISSUE TITLE
SVG translator fails on some files

### ISSUE THREAD

**Issue by humdingerb** [threedeyes/NanoSVGTranslator#2]
Originally reported at the Haiku bugtracker: https://dev.haiku-os.org/ticket/16615

Many SVGs display in ShowImage just fine, but some don't and are just black. Attached are two SVGs from the backgrounds contest.

Dahyun Lee's Momiji flow: https://dev.haiku-os.org/attachment/ticket/16615/001_Momiji_flow.svg

zuMi's Cociu: https://dev.haiku-os.org/attachment/ticket/16615/cociu.svg

**Comment by threedeyes** [comment]
Fixed in https://github.com/threedeyes/NanoSVGTranslator/commit/38519ba3fe0a679daf30e2d2b823a976a7bec03e
